### ISSUE TITLE
ss可以连，但是kcp连不上

### ISSUE THREAD

**Issue by ferristale** [shadowsocks-plus/shadowsocks-plus#1]
2016/07/17 23:31:08 [ERR] yamux: keepalive failed: i/o deadline reached
2016/07/17 23:31:20 stream closed
2016/07/17 23:31:21 session shutdown
2016/07/17 23:31:21 nodelay parameters: 0 20 2 1
2016/07/17 23:31:21 remote address: 3.3.3.3:3
2016/07/17 23:31:21 sndwnd: 128 rcvwnd: 1024
2016/07/17 23:31:21 mtu: 1350
2016/07/17 23:31:21 fec: 4
2016/07/17 23:31:21 acknodelay: false
2016/07/17 23:31:21 dscp: 46

**Comment by losfair** [comment]
目前的代码结构问题太多，我正在尝试用 ANSI C 重构一部分代码并开源。目前的版本中 kcptun 相关的逻辑是有问题的。
