### ISSUE TITLE
hello, 编译不通过

### ISSUE THREAD

**Issue by winds3991** [shadowsocks-plus/shadowsocks-plus#17]
环境，Centos7，golang 1.7
问题，
``../github.com/shadowsocks-plus/kcptun-integration/kcptun/server.go:259: conn.SetStreamMode undefined (type net.Conn has no field or method SetStreamMode) 
``
请问该怎么解决

**Comment by jm33-m0** [comment]
请参考我之前的评论 [https://github.com/shadowsocks-plus/shadowsocks-plus/issues/3](https://github.com/shadowsocks-plus/shadowsocks-plus/issues/3)
