### ISSUE TITLE
一键脚本有点问题，centos6

### ISSUE THREAD

**Issue by ThomasLiaoQian** [shadowsocks-plus/shadowsocks-plus#2]
看了下脚本，libssplus.so文件是下载到/usr/lib的，而ssplus-server又是下到/usr/bin的，执行的时候会提示找不到libssplus.so
所以需要将libssplus.so文件链接到/usr/bin下
ln -s /usr/lib/libssplus.so /usr/bin
ldconfig
但即便如此，执行以后一直提示bad server response，大概是这个，没继续使用了，希望能完善，或者教程说明更清晰一点

**Comment by losfair** [comment]
共享库的搜索路径包含 /usr/lib 但不包含可执行文件的当前目录，因此应该是不需要重新链接的，能确认是这里的问题吗？
目前的代码结构问题太多，我正在尝试用 ANSI C 重构一部分代码并开源。

**Comment by ferristale** [comment]
对我刚试了一下，不停返回WARNING: Bad response from server
客户端返回的就在我的issue里
