### ISSUE TITLE
ss without kcp客户端速度远高于ss+自带客户端（server端都是ss+）

### ISSUE THREAD

**Issue by jm33-m0** [shadowsocks-plus/shadowsocks-plus#4]
>我的宽带是移动50Mbps对等，使用kcptun+ss的时候不知道是不是参数问题，速度比单独ss还要慢很多很多

1. 这个是使用ss+的客户端

![ss-kcp](https://cloud.githubusercontent.com/assets/10167884/17541619/d0b13dd8-5ef3-11e6-96f9-c99301875399.png)

2. 这个是使用ss win的客户端（python版本的linux客户端测速结果也一样，OpenWrt上的ss libev测速结果和ss+测速结果相比稍弱）

![ss-no-kcp](https://cloud.githubusercontent.com/assets/10167884/17541623/dda0769e-5ef3-11e6-8d86-32cc1b2be606.png)

**Comment by losfair** [comment]
可能是你的运营商对 UDP 协议做了限速。
能否提供一下使用 SSPlus 后的流量比例？

**Comment by jm33-m0** [comment]
你是指UDP和TCP的比例么？有没有什么工具可以做这样的统计?

**Comment by losfair** [comment]
下载一个大文件，查看消耗的流量。（服务器端 ifconfig 看前后差值即可）

**Comment by jm33-m0** [comment]
下载一个ISO镜像文件，下载到114MB的时候数据从
`RX 13.2GB TX 27.0GB`
变成了
`RX 13.3GB TX 28.2GB`

看上去似乎有很多重发的包。。

**Comment by jm33-m0** [comment]
如果使用Python版本的sslocal，则基本没有重发
`RX 13.5GB TX 29.3GB`到
`RX 13.7GB TX 29.5GB`

文件下载大小是217MB

**Comment by jm33-m0** [comment]
也就是说，没有kcp的时候速度正常。如果只依靠路由器上的ss libev速度会受限在20mbps左右，在此基础上测试，直接在电脑上运行sslocal的话基本满速，加上kcp之后速度开始不稳定且无法跑满带宽

**Comment by losfair** [comment]
应该是运营商做了 UDP 限速。
我这两天看看有没有解决方案。
