### ISSUE TITLE
安卓新版的带kcp不能用

### ISSUE THREAD

**Issue by tianlichunhong** [shadowsocks-plus/shadowsocks-plus#8]
别说kcp，就是去掉kcp，也用不了。我手机是安卓4.4.2的。换回老版本能用。

**Comment by jm33-m0** [comment]
![tmp_2222-screenshot_2016-08-21-22-46-43-153610382](https://cloud.githubusercontent.com/assets/10167884/17837857/33dbc760-67f1-11e6-863c-1eda5360d1a0.jpg)

**Comment by icefairy** [comment]
--key "SSplus_Key_NOTsecret"
方便复制…

**Comment by icefairy** [comment]
手机端还是用不了 已经按图中设置好了 端口加一万 --key "SSplus_Key_NOTsecret"也设置了 一旦开启kcp就打不开网页了 关闭kcp就没问题 你们都正常吗

**Comment by tianlichunhong** [comment]
正常，我用的是安卓4.4。运行良好。

**Comment by icefairy** [comment]
我系统6.0的 魔趣的rom，ss客户端用的googleplay最新版的，你就是设置kcp参数--key "SSplus_Key_NOTsecret" 就可以用了吗？有没有单独运行kcptun之类的？我电脑上都可以用呢不过是用的作者提供的sspwin客户端手机上只能用纯ss

**Comment by tianlichunhong** [comment]
影梭是不需要其他kcptun程序的。已经集成了客户端。如果你部署的kcptun服务器，在你的电脑能用，使用同样的参数，在影梭也能用。

**Comment by icefairy** [comment]
电脑上可以用。。ssp客户端，手机上就不能。。我有一个vps自己用ss手工搭建的kcptun 就可以用~ 所以应该也不是运营商封udp之类的原因

**Comment by icefairy** [comment]
另外我在好几个vps上搭建了ssp都是一样的 电脑上可以用 手机上不能 （kcp）

**Comment by icefairy** [comment]
对了 我能用的那个机子是单独安的ss然后用https://raw.githubusercontent.com/kuoruan/kcptun_installer/master/kcptun.sh
这个脚本安装的kcptun 就可以连接，用ssp脚本安装的 在手机上只有ss工作正常

**Comment by icefairy** [comment]
我在之前用ssp搭建的vps上用了这个脚本安装了一个kcptun在手机上也能用了~ 手机端连接参数用的：-autoexpire 60 -key "pass" -crypt "aes-128" -mode "fast"

**Comment by zhuhangyu** [comment]
一样，我也是安卓7.0开kcp就用不了，不开kcp能翻。电脑上开kcp正常。
